### PR TITLE
tracing: utxocache tracepoints follow-up 

### PR DESCRIPTION
**Pull request by arnabsen1729**
This PR is a follow-up to the [#22902](https://github.com/bitcoin/bitcoin/pull/22902). 

Previously, the tracepoint `utxocache:flush` was called, even when it was not flushing. So, the tracepoint is now scoped to write only when coins cache to disk.

### CODE REVIEW

**Comment by 0xB10C** [comment]
This still mentions "Is called *after* the **caches and indexes** are flushed depending on the mode" in docs/tracing.md.

You can drop the indexes part.

**Comment by arnabsen1729** [comment]
> This still mentions "Is called _after_ the **caches and indexes** are flushed depending on the mode" in docs/tracing.md.
> 
> You can drop the indexes part.

Removed that in e823c5c

**Comment by 0xB10C** [comment]
I've added another commit (https://github.com/0xB10C/bitcoin/commit/0407530d7d43fb1ec4b500b4b90e6e9d2ae373b6) to https://github.com/0xB10C/bitcoin/tree/2021-12-utxocache-tracepoint-fixups, please add this one here.

You should be able to use e.g. `git cherry-pick` to include my four commits in your branch. Once that's done, don't squash them yet. 

We can squash them into two commits once we are somewhat certain that we have covered all low hanging follow-ups. For my commits it makes sense to include the squashed commit messages (subject and body) in the commit message body of the squash commit.  

Similar to:
```
tracing: drop unneeded argument from utxocache:flush (author arnab, your two squashed commits)
tracing: misc follow-ups to 22902 (author 0xb10c, my four squashed commits)
```

**Comment by arnabsen1729** [comment]
- Cherry-picked your last commit https://github.com/0xB10C/bitcoin/pull/3/commits/29685d0ae26c8c86638549bbe940604a164b1a5b
- Update the commit message of https://github.com/0xB10C/bitcoin/pull/3/commits/f9c77c5597e8a1ed441b81414d4711baefc667c2

**Comment by 0xB10C** [comment]
Thanks, however that's not exactly what I meant. Some of my fixup commits are mixed into your first commit. Please separate them cleanly :) Maybe it's easier to do this on a clean branch, then delete `arnabsen1729:2021-12-utxocache-usdt-fix` locally and create a new branch named `2021-12-utxocache-usdt-fix` from the clean branch and force push the new `2021-12-utxocache-usdt-fix`. LMK if you need help with this.

**Comment by arnabsen1729** [comment]
@0xB10C 
https://github.com/0xB10C/bitcoin/pull/3/commits/6e54570b554389e52bcff2fa534dc195f3953203 -> your 4 commits which I cherry picked
https://github.com/0xB10C/bitcoin/pull/3/commits/6e54570b554389e52bcff2fa534dc195f3953203 -> my 2 commits

If you update your master branch probably the rest of the commits will be gone.

**Comment by 0xB10C** [comment]
Thanks, this looks good! But I still have two things to fixup regrading commit messages :smile:

1. You mention this in the PR description, but it should be mentioned in the commit message of your commit too:
  - > Previously, the `utxocache:flush` tracepoint was in the wrong scope and reached every time `CChainState::FlushStateToDisk` was called, even when we don't flush. The tracepoint is now properly scoped to be reached only when we full flush.
  - It might also make sense to reword the commit subject (I know put the current subject as an example in https://github.com/0xB10C/bitcoin/pull/3#issuecomment-992673727, but I don't think it makes sense anymore). The primary action we do is putting the tracepoint in the correct scope, that we drop an unneeded argument is only an effect of that. Maybe something like: `tracing: correctly scope utxocache:flush tracepoint`. You can mention that we can now drop the last argument.
2. When squashing via `git rebase` it gives you the option to keep the commit messages of the to-be-squashed commits. I think, if we include a `misc follow-ups` commit we should at-least keep the original commit messages in the body. This makes a misc follow-ups commit way easier to understand.

In general, I think it's very helpful to look at it from a reviewer perspective. Imagine you click on a random PR to review and you don't know anything about it yet. It becomes a lot easier to review when the commits detail why something is done. We don't write these messages for someone familiar with the previous PR (e.g. you or me), we write them for normal reviewers without any prior knowledge. That's why I'm nitpicking this so much.

**Comment by arnabsen1729** [comment]
@0xB10C I tried to follow your points

- updated the commit title of https://github.com/0xB10C/bitcoin/pull/3/commits/38a59c2ae63fb6b6144d5804fe6d1b36d4baeff6 and added more context in the commit body.
- I manually copied the commit titles and the description and added it to the description for the https://github.com/0xB10C/bitcoin/pull/3/commits/235addd7e12ad5f129bac8f2bdc00859dadbdd19.

**Comment by 0xB10C** [comment]
@arnabsen1729 Awesome! LGTM. Feel free to close this and open it against bitcoin/bitcoin. I'll do further testing there.

**Comment by arnabsen1729** [comment]
@0xB10C Is the PR title and body fine, Is there anything I must specify/change?

**Comment by 0xB10C** [comment]
Yes, LGTM!

**Pull request closed without merging**
